app/routes/main/routes.py
from flask import render_template, request, url_for, redirect, flash, session, g, request,session,Blueprint


from app.models.user import Operation
from .. import login_required



main_bp = Blueprint('main', __name__, template_folder='../../templates/main', static_folder='../../static')

# ruta principal de inicio
@main_bp.route('/')
def index():
    return render_template('main/index.html')

# proyecto flujorad web
@main_bp.route('/flujorad')
def flujorad():
    return render_template('proyectos/flujorad.html')

@main_bp.route('/perfil')
@login_required
def panel_user():
    return render_template('perfil/panel.html')

@main_bp.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def update_profile():
    if not g.user:
        flash('Debes iniciar sesión para editar tu perfil', 'danger')
        return redirect(url_for('user.login'))

    user = g.user
    if request.method == 'POST':
        user.first_name = request.form['firstName']
        user.last_name = request.form['lastName']
        user.email = request.form['email']
        user.phone = request.form['phone']
        user.username = request.form['username']
        user.document_id = request.form['document_id']
        
        try:
            user.save()  # Guardar cambios en la base de datos
            flash('Perfil actualizado con éxito', 'success')
            session['user_id'] = user.id
            Operation.create(user=user, event_type='update_profile', description='Perfil actualizado.')
            return redirect(url_for('main.panel_user'))
        except Exception as e:
            flash('Error al actualizar el perfil: {}'.format(e), 'danger')

    return render_template('perfil/edit_profile.html', user=user)

app/templates/main/perfil/edit_profile.html
{% extends "base.html" %}

{% block titulo %} EDITAR PERFIL {% endblock %}

{% block content %}
<section id="features" class="ud-features">
  <div class="container mt-4">
    <h2 class="text-center mb-4">Editar Perfil</h2>

    <!-- Mensajes de flash -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="alert alert-dismissible fade show" role="alert">
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} mb-3">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    <form id="editProfileForm" method="POST" action="{{ url_for('main.update_profile') }}">
        <div class="row">
            <!-- Nombre -->
            <div class="col-md-6 mb-3">
                <label for="firstName" class="form-label">Nombre</label>
                <input type="text" class="form-control" id="firstName" name="firstName" value="{{ user.first_name }}" required>
            </div>
            <!-- Apellidos -->
            <div class="col-md-6 mb-3">
                <label for="lastName" class="form-label">Apellidos</label>
                <input type="text" class="form-control" id="lastName" name="lastName" value="{{ user.last_name }}" required>
            </div>
        </div>
        <div class="row">
            <!-- Correo Electrónico -->
            <div class="col-md-6 mb-3">
                <label for="email" class="form-label">Correo Electrónico</label>
                <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}" required>
            </div>
            <!-- Teléfono -->
            <div class="col-md-6 mb-3">
                <label for="phone" class="form-label">Teléfono</label>
                <input type="text" class="form-control" id="phone" name="phone" value="{{ user.phone }}" required>
            </div>
            
        </div>
        <div class="row">
            <!-- Nombre de Usuario -->
            <div class="col-md-6 mb-3">
                <label for="username" class="form-label">Nombre de Usuario</label>
                <input type="text" class="form-control" id="username" name="username" value="{{ user.username }}" required>
            </div>
            <!-- Carnet de identidad -->
            <div class="col-md-6 mb-3">
                <label for="username" class="form-label">Carnet de identidad</label>
                <input type="text" class="form-control" id="documentid" name="document_id" value="{{ user.document_id }}" required>
            </div>
        </div>
        
        <div class="d-flex justify-content-end mt-3">
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </div>
    </form>
  </div>
</section>
{% endblock %}

app/templates/main/perfil/panel.html
{% extends "base.html" %}

{% block titulo %} PERFIL {% endblock %}

{% block content %}
<section id="features" class="ud-features">
    <div class="container mt-4">
    <div class="row">
        <div class="col-12 text-center mb-4">
            <h1 class="text-primary">Bienvenido, {{ g.user.first_name }} {{ g.user.last_name }}</h1>
            <p class="text-secondary">Este es tu panel de usuario. Desde aquí puedes gestionar tus configuraciones y actividades.</p>
            {% with messages = get_flashed_messages(with_categories=true) %}
               {% if messages %}
            <div class="alert alert-dismissible fade show" role="alert">
                  {% for category, message in messages %}
                    <div class="alert alert-{{ category }} mb-3">{{ message }}</div>
                  {% endfor %}
            </div>
               {% endif %}
            {% endwith %}
          </div>
    </div>
     
    <!-- Información general del usuario -->
    <div class="row mb-4">
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">Información Personal</h5>
                    <p class="card-text"><strong>Nombre:</strong> {{ g.user.first_name }} {{ g.user.last_name }}</p>
                    <p class="card-text"><strong>Correo:</strong> {{ g.user.email }}</p>
                    <p class="card-text"><strong>Teléfono:</strong> {{ g.user.phone }}</p>
                </div>
            </div>
        </div>

        <!-- Enlaces rápidos -->
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">Opciones rápidas</h5>
                    <ul class="list-unstyled">
                        <li><a href="  {{ url_for('main.update_profile') }}" class="text-primary">Actualizar perfil</a></li>
                        <li><a href="{{ url_for('user.reset_password') }}" class="text-primary">Restablecer contraseña</a></li>
                        {% if g.user.rol == 'administrador' %}
                        <li><a href="{{ url_for('user.admin_panel') }}" class="text-primary">Panel del administrador</a></li>
                        {% endif %}
                        {% if g.user.rol == 'usuario TCP' %}
                        <li><a href="{{ url_for('tcp.panel_tcp') }}" class="text-primary">Panel del Negocio TCP</a></li>
                        {% endif %}
                        {% if g.user.rol == 'estadístico' %}
                        <li><a href="#" class="text-primary">Panel del Estadistico</a></li>
                        {% endif %}
                        <li><a href="#" class="text-primary">Eliminar cuenta</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- Tabla de actividades recientes -->
    <div class="row">
        <div class="col-12">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">Últimas Operaciones</h5>
                    <select id="event-filter">
                        <option value="all">Todos</option>
                        <option value="login">Inicio de sesión</option>
                        <option value="update_profile">Actualización de perfil</option>
                        <option value="purchase">Compra</option>
                    </select>
                    <table id="operations-table" class="table table-striped">
                        <thead>
                            <tr>
                                <th>Evento</th>
                                <th>Descripción</th>
                                <th>Fecha y Hora</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Se llenará dinámicamente -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
    </div>
</section>
<script src="{{ url_for('static', filename='js/user/profile.js') }}"></script>
{% endblock %}