app/models/user.py
from peewee import  *
from datetime import date, datetime
from werkzeug.security import generate_password_hash, check_password_hash
from wtforms import DecimalField, FloatField


from app.database import  BaseModel





class User(BaseModel):
    id = AutoField(primary_key=True)
    first_name = CharField(max_length=50)
    last_name = CharField(max_length=50)
    email = CharField(max_length=100, unique=True)
    username = CharField(max_length=50, unique=True)
    phone = CharField(max_length=15, unique=True)  # Nuevo campo
    document_id = CharField(max_length=9, unique=True)
    password = CharField(max_length=255)
    rol = CharField(max_length=20, default='usuario')
    cargo = CharField(max_length=50)
    license_duration = CharField(null=True)  # Duración en meses para el rol TCP
    license_expiry = DateTimeField(null=True)   # Fecha de expiración del rol TCP
    verified = BooleanField(default=False)
    
    class Meta:
        table_name = 'user'

    def days_remaining(self):
        """Calcula los días restantes de la licencia"""
        if self.license_expiry:
            today = date.today()
            today_datetime = datetime.combine(today, datetime.min.time())
            remaining_days = (self.license_expiry - today_datetime).days
            return remaining_days if remaining_days > 0 else 0
        return 0

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)
    


class Operation(BaseModel):
     EVENT_TYPES = (
        ('login', 'Inicio de sesión'),
        ('update_profile', 'Actualización de perfil'),
        ('update_type_user', 'Cambio de tipo de usuario en el sistema'),
        ('logout', 'Cierre de sesión'),
        ('rest_password', 'Restablecimiento de contraseña'),
        ('crear_producto', 'Crear un producto'),
    )

     user = ForeignKeyField(User, backref='operations')
     event_type = CharField(choices=EVENT_TYPES)
     description = TextField()
     created_at = DateTimeField(default=datetime.now)

app/user/models.py
from peewee import Model, CharField, AutoField
from app import db
from werkzeug.security import generate_password_hash, check_password_hash

class BaseModel(Model):
    class Meta:
        database = db

class User(BaseModel):
    id = AutoField(primary_key=True)
    first_name = CharField(max_length=50)
    last_name = CharField(max_length=50)
    email = CharField(max_length=100, unique=True)
    username = CharField(max_length=50, unique=True)
    phone = CharField(max_length=15, unique=True)  # Nuevo campo
    password = CharField(max_length=255)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

app/routes/user/routes.py
from peewee import fn,JOIN
from datetime import datetime, timedelta
from flask import current_app, jsonify, render_template, request, url_for, redirect, flash, session, g, request,session,Blueprint
from werkzeug.security import generate_password_hash, check_password_hash
import re

from app.config import confirm_token, generate_confirmation_token
from app.models import user
from app.models.tcp import TCPBusiness
from app.models.user import Operation, User
from app.email_service import generate_reset_token, send_email, verify_reset_token
from .. import login_required, admin_required

user_bp = Blueprint('user', __name__, template_folder='../../templates/user', static_folder='../../static')

@user_bp.route('/registro',methods = ('GET', 'POST'))
def registro():
     if request.method == 'POST':
        # Obtener datos del formulario
        first_name = request.form.get('firstName')
        last_name = request.form.get('lastName')
        email = request.form.get('email')
        username = request.form.get('username')
        password = request.form.get('password')
        confirm_password = request.form.get('confirmPassword')
        phone = request.form.get('phone')
         
        # Validar datos
        errors = []
        # Regla de contraseña compleja
        password_regex = r'^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*.?&]{8,}$'
       
        if not first_name or not last_name:
            errors.append("El nombre y los apellidos son obligatorios.")
        
        if not email or '@' not in email:
            errors.append("El correo electrónico no es válido.")
        
        if not username:
            errors.append("El nombre de usuario es obligatorio.")
        elif User.select().where(User.username == username).exists():
            errors.append("El nombre de usuario ya está en uso.")
        
        if not phone or not phone.isdigit():
            errors.append("El teléfono debe ser un número válido.")
        elif User.select().where(User.phone == phone).exists():
            errors.append("ERl telefono ya esta en uso.")

        
        if not re.match(password_regex, password):
           errors.append('La contraseña debe tener al menos 8 caracteres, incluir una mayúscula, un número y un carácter especial.')
        

        if not password:
            errors.append("La contraseña es obligatoria.")
        elif password != confirm_password:
            errors.append("Las contraseñas no coinciden.")

        if User.select().where(User.email == email).exists():
            errors.append("El correo electrónico ya está registrado.") 
       
        if errors:
            for error in errors:
                flash(error, 'error')
            return render_template('register.html',errors=errors) 
        # Crear usuario
        try:
            hashed_password = generate_password_hash(password)
            new_user = User.create(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=username,
                password=hashed_password,
                phone=phone,
                verified=False
                ) 
            token = generate_confirmation_token(new_user.email)
            confirm_url = url_for('user.confirm_email', token=token, _external=True)
        
            # Enviar correo de verificación
            subject = "Verificación de correo electrónico"
            recipients = [new_user.email]
            template = 'email/verify_email.html'
            context = {'username': new_user.username, 'confirm_url': confirm_url}
            send_email(subject, recipients, template, **context)

            flash('Te hemos enviado un correo para verificar tu cuenta.', 'success')
            return redirect(url_for('user.login'))
        except Exception as e:
            current_app.logger.error(f"Error registrando usuario: {e}")
            flash('Ocurrió un error al registrar al usuario.', 'danger')

        
     return render_template('register.html')

@user_bp.route('/resend-verification-email', methods=['POST'])
def resend_verification_email():
    email = request.form.get('resend_email')
    user = User.get_or_none(User.email == email)
    
    if not user:
        flash('El correo ingresado no está registrado.', 'danger')
        return redirect(url_for('user.login'))
    
    if user.verified:
        flash('Tu cuenta ya está verificada.', 'info')
        return redirect(url_for('user.login'))
    
    # Generar y enviar el enlace de verificación
    token = generate_confirmation_token(user.email)
    verification_url = url_for('user.confirm_email', token=token, _external=True)
    subject = "Verifica tu cuenta"
    recipients = [user.email]
    template = 'email/verify_email.html'
    context = {'username': user.username, 'confirm_url': verification_url}
    send_email(subject, recipients, template, **context)
    flash('Te hemos enviado un enlace de verificación a tu correo.', 'info')
    return redirect(url_for('user.login'))
    
@user_bp.route('/confirm/<token>')
def confirm_email(token):
    try:
        email = confirm_token(token)
        if not email:
            flash('El enlace de verificación es inválido o ha expirado.', 'danger')
            return redirect(url_for('login'))

        user = User.get(User.email == email)
        
        if user.verified:
            flash('Tu cuenta ya está verificada. Por favor, inicia sesión.', 'info')
        else:
            user.verified = True
            user.save()
            user_reloaded = User.get(User.id == user.id)
            print(f"Verified value after save: {user_reloaded.verified}")

            # Enviar correo de bienvenida
            subject = "¡Bienvenido a nuestra aplicación!"
            recipients = [user.email]
            template = 'email/welcome.html'
            context = {'username': user.username}
            send_email(subject, recipients, template, **context)

            flash('Tu cuenta ha sido verificada exitosamente.', 'success')
        return redirect(url_for('user.login'))
    except Exception as e:
        current_app.logger.error(f"Error verificando correo: {e}")
        flash('Ocurrió un error al verificar tu correo.', 'danger')
        return redirect(url_for('user.login'))
# inicio de seccion del usuario

@user_bp.route('/login',methods = ('GET', 'POST'))
def login():
    if request.method == 'POST':
        username_or_email = request.form.get('userOrEmail')
        password = request.form.get('password')

        # Buscar usuario por nombre de usuario o correo
        user = User.select().where(
            (User.username == username_or_email) | 
            (User.email == username_or_email) 
        ).first()
    #    print(user.verified)

        if not User.verified:
                flash('Tu cuenta no ha sido verificada. Por favor, revisa tu correo.', 'warning')
                return redirect(url_for('user.login'))
         # Buscar usuario por nombre de usuario o correo
        if not user:
            # Usuario o correo no encontrados
            flash('Usuario o contraseña incorrectos..', 'danger')
            return render_template('login.html')

        if not user.check_password(password):
            # Contraseña incorrecta
            flash('Usuario o contraseña incorrectos.', 'danger')
            return render_template('login.html')
       
        negocios_ids = [negocio.id for negocio in  TCPBusiness.select( TCPBusiness.id).where( TCPBusiness.user_id == user)]
        print(negocios_ids)     

        session['user_id'] = user.id
        session['username'] = user.username
        session['nombre_completo'] = f"{user.first_name} {user.last_name}"
        session['cargo'] = user.cargo
        session['negocio_id'] = negocios_ids 
        session['url_history'] = []
        flash('Inicio de sesión exitoso.', 'success')
        
        Operation.create(user=user, event_type='login', description='Inicio de sesión exitoso.')
        return redirect(url_for('main.panel_user'))
    return render_template('login.html')

# Restablecer contraseña
@user_bp.route('/reset_password',methods = ('GET', 'POST'))
def reset_password():
     if request.method == 'POST':
        email = request.form.get('email')
        user = User.get_or_none(User.email == email)
        usuario = g.user.first_name +" "+ g.user.last_name
        if user:
            # Generar token
            token = generate_reset_token(email)
            # URL de restablecimiento
            reset_url = url_for('user.token_password', token=token, _external=True)
            # Enviar correo
            send_email(
                subject="Restablecimiento de contraseña",
                recipients=[email],
                template="email/reset_password.html",
                title="Restablece tu contraseña",
                reset_url=reset_url,
                usuario=usuario
            )
            flash("Se ha enviado un correo con instrucciones para restablecer tu contraseña.", "success")
        else:
            flash("El correo no está registrado.", "danger")
        return redirect(url_for('user.reset_password'))
         
     return render_template('reset_password.html')

@user_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
def token_password(token):
    email = verify_reset_token(token)
    if not email:
        flash("El enlace de restablecimiento es inválido o ha expirado.", "danger")
        return redirect(url_for('user.reset_password'))
    
    if request.method == 'POST':
        new_password = request.form.get('password')
        user = User.get_or_none(User.email == email)
        if user:
            # Actualizar contraseña
            user.set_password(new_password)  # Asegúrate de tener un método para encriptar la contraseña
            user.save()

            flash("Tu contraseña ha sido actualizada exitosamente.", "success")
            session['user_id'] = user.id

app/user/routes.py
from flask import Blueprint, render_template, request, url_for, redirect, flash, session, g, request,session
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from app.user import user_bp
import re


#registro de usuarios
@user_bp.route('/registro',methods = ('GET', 'POST'))
def registro():
     if request.method == 'POST':
        # Obtener datos del formulario
        first_name = request.form.get('firstName')
        last_name = request.form.get('lastName')
        email = request.form.get('email')
        username = request.form.get('username')
        password = request.form.get('password')
        confirm_password = request.form.get('confirmPassword')
        phone = request.form.get('phone')
         
        # Validar datos
        errors = []
        # Regla de contraseña compleja
        password_regex = r'^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*.?&]{8,}$'
       
        if not first_name or not last_name:
            errors.append("El nombre y los apellidos son obligatorios.")
        
        if not email or '@' not in email:
            errors.append("El correo electrónico no es válido.")
        
        if not username:
            errors.append("El nombre de usuario es obligatorio.")
        elif User.select().where(User.username == username).exists():
            errors.append("El nombre de usuario ya está en uso.")
        
        if not phone or not phone.isdigit():
            errors.append("El teléfono debe ser un número válido.")
        elif User.select().where(User.phone == phone).exists():
            errors.append("ERl telefono ya esta en uso.")

        
        if not re.match(password_regex, password):
           errors.append('La contraseña debe tener al menos 8 caracteres, incluir una mayúscula, un número y un carácter especial.')
        

        if not password:
            errors.append("La contraseña es obligatoria.")
        elif password != confirm_password:
            errors.append("Las contraseñas no coinciden.")

        if User.select().where(User.email == email).exists():
            errors.append("El correo electrónico ya está registrado.") 
       
        if errors:
            for error in errors:
                flash(error, 'error')
            return render_template('register.html',errors=errors) 
        # Crear usuario
        hashed_password = generate_password_hash(password)
        new_user = User.create(
            first_name=first_name,
            last_name=last_name,
            email=email,
            username=username,
            password=hashed_password,
            phone=phone
        ) 

        # Redirigir al inicio de sesión con mensaje de éxito
        flash("Usuario registrado con éxito. Por favor, inicia sesión.", 'success')
        return redirect(url_for('user.login'))
     return render_template('register.html')

# inicio de seccion del usuario
@user_bp.route('/login',methods = ('GET', 'POST'))
def login():
    if request.method == 'POST':
        username_or_email = request.form.get('userOrEmail')
        password = request.form.get('password')

        # Buscar usuario por nombre de usuario o correo
        user = User.select().where(
            (User.username == username_or_email) | 
            (User.email == username_or_email)
        ).first()
        
         # Buscar usuario por nombre de usuario o correo
        if not user:
            # Usuario o correo no encontrados
            flash('Usuario o contraseña incorrectos..', 'danger')
            return render_template('login.html')

        if not user.check_password(password):
            # Contraseña incorrecta
            flash('Usuario o contraseña incorrectos.', 'danger')
            return render_template('login.html')
            

        session['user_id'] = user.id
        session['username'] = user.username
        flash('Inicio de sesión exitoso.', 'success')
        return redirect(url_for('main.panel_user'))

        

        
    
    return render_template('login.html')
# Restablecer contraseña
@user_bp.route('/reset_password',methods = ('GET', 'POST'))
def reset_password():

    return render_template('reset_password.html')

@user_bp.route('/logout')
def logout_user():
    session.clear()
    flash('Has cerrado sesión.', 'info')
    return redirect(url_for('main.index'))

@user_bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id:
        g.user = User.get_or_none(User.id == user_id)
    else:
        g.user = None

app/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar Sesión</title>
    <!-- Enlace a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Enlace a los estilos -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user/styles_login.css') }}">


    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/icol_logo.ico') }}"
      type="image/svg"
    />
</head>
<body>
    <div class="login-container">
        <h3 class="text-center mb-4">Iniciar Sesión</h3>
        <form id="loginForm" method="POST" action="{{ url_for('user.login') }}">
            <!-- Usuario o Correo -->
            <div class="mb-3">
                <label for="userOrEmail" class="form-label">Usuario o Correo Electrónico</label>
                <input type="text" class="form-control" id="userOrEmail" name="userOrEmail" placeholder="Ingresa tu usuario o correo" required>
                
            </div>
            <!-- Contraseña -->
            <div class="mb-3">
                <label for="password" class="form-label">Contraseña</label>
                <input type="password" class="form-control"  id="password" name="password" placeholder="Ingresa tu contraseña" required>
                
            </div>
            <!-- Botón de Iniciar Sesión -->
            <button type="submit" class="btn btn-primary w-100">Iniciar Sesión</button>
           
        </form>

        <hr>

            <!-- Nuevo formulario para reenviar el correo de verificación -->
        <form method="POST" action="{{ url_for('user.resend_verification_email') }}">
          <h5>¿No has verificado tu correo?</h5>
           <div class="mb-3">
             <label for="resend_email">Introduce tu correo para reenviar el enlace de verificación</label>
             <input type="email" id="resend_email" name="resend_email" class="form-control" required>
          </div>
             <button type="submit" class="btn btn-secondary w-100">Reenviar Verificación</button>
       </form>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="mt-2">
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
        <!-- Enlaces -->
        <div class="text-center mt-3">
            <a href="{{ url_for('user.registro') }}">¿No tienes cuenta? Regístrate</a><br>
            <a href="{{ url_for('user.reset_password') }}">¿Olvidaste tu contraseña?</a>
        </div>
    </div>

    <!-- Enlace a Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Enlace al archivo de scripts -->
    
</body>
</html>

app/templates/user/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de Usuario</title>
    <!-- Enlace a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Enlace a los estilos -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user/styles_registro.css') }}"> 

    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/icol_logo.ico') }}"
      type="image/svg"
    />
</head>
<body>
    <div class="register-container">
        <h3 class="text-center mb-4">Registro de Usuario</h3>
        <form method="POST" action="{{ url_for('user.registro') }}" id="registerForm">
            <!-- Nombre -->
            <div class="mb-3">
                <label for="firstName" class="form-label">Nombre</label>
                <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Ingresa tu nombre" required>
                <div class="form-alert text-danger">El nombre es obligatorio.</div>
            </div>
            <!-- Apellidos -->
            <div class="mb-3">
                <label for="lastName" class="form-label">Apellidos</label>
                <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Ingresa tus apellidos" required>
                <div class="form-alert text-danger">Los apellidos son obligatorios.</div>
            </div>
            <!-- Correo -->
            <div class="mb-3">
                <label for="email" class="form-label">Correo Electrónico</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="ejemplo@correo.com" required>
                <div class="form-alert text-danger">Ingresa un correo válido.</div>
            </div>
            <!-- telefono -->
            <div class="mb-3">
              <label for="phone" class="form-label">Teléfono</label>
              <input type="tel" class="form-control" id="phone" name="phone" placeholder="Ingresa tu número de teléfono" required>
              <div class="form-alert text-danger">Ingresa un número de teléfono válido.</div>
          </div>
            <!-- Usuario -->
            <div class="mb-3">
                <label for="username" class="form-label">Usuario</label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Elige un nombre de usuario" required>
                <div class="form-alert text-danger">El nombre de usuario es obligatorio.</div>
            </div>
            <!-- Contraseña -->
            <div class="mb-3">
                <label for="password" class="form-label">Contraseña</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Elige una contraseña" required>
                <div class="form-alert text-danger">La contraseña es obligatoria.</div>
            </div>
            <!-- Repetir Contraseña -->
            <div class="mb-3">
                <label for="confirmPassword" class="form-label">Confirmar Contraseña</label>
                <input type="password" class="form-control" id="confirmPassword" name="confirmPassword" placeholder="Repite la contraseña" required>
                <div class="form-alert text-danger">Las contraseñas no coinciden.</div>
            </div>
            <!-- Botón de Registro -->
            <button type="submit" class="btn btn-primary w-100">Registrarse</button>
            <div id="generalError" class="form-alert text-danger mt-2">Por favor, corrige los errores antes de continuar.</div>
        </form>
		{% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            <div class="alert alert-danger">
              <ul>
               {% for category, message in messages %}
                 <li>{{ message }}</li>
               {% endfor %}
              </ul>
            </div>
          {% endif %}
        {% endwith %}
        <!-- Enlace al inicio de sesión -->
        <div class="text-center mt-3">
            <a href="{{ url_for('user.login') }}">¿Ya tienes una cuenta? Inicia sesión</a>
        </div>
    </div>

    <!-- Enlace a Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Enlace al archivo de scripts -->
    
</body>
</html>

app/templates/user/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restablecer Contraseña</title>
    <!-- Enlace a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Enlace a los estilos -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user/styles_reset_passwor.css') }}">

    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/icol_logo.ico') }}"
      type="image/svg"
    />
</head>
<body>
    <div class="reset-container">
        <h3 class="text-center mb-4">Restablecer Contraseña</h3>
        <form id="resetPasswordForm" method="POST" action="{{ url_for('user.reset_password') }}">
            <!-- Correo Electrónico -->
            <div class="mb-3">
                <label for="email" class="form-label">Correo Electrónico</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Ingresa tu correo electrónico" required>
               
            </div>
            <!-- Botón de Restablecer Contraseña -->
            <button type="submit" class="btn btn-primary w-100">Enviar Instrucciones</button>
            
        </form>
        {% with messages = get_flashed_messages(with_categories=true) %}
           {% if messages %}
            <div class="mt-2">
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">{{ message }}</div>
                {% endfor %}
            </div>
          {% endif %}
        {% endwith %}
        <!-- Enlace para volver -->
        <div class="text-center mt-3">
            <a href="{{url_for('user.login')}}">¿Ya tienes una cuenta? Inicia Sesión</a>
        </div>
    </div>

    <!-- Enlace a Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Enlace al archivo de scripts -->
    
</body>
</html>

app/templates/user/update_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restablecer Contraseña</title>
    <!-- Enlace a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Enlace a los estilos -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user/styles_reset_passwor.css') }}">

    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/icol_logo.ico') }}"
      type="image/svg"
    />
</head>
<body>
    <div class="reset-container">
        <h3 class="text-center mb-4">Escriba la nueva contraseña</h3>
           <form method="POST">
              <div class="mb-3">
                  <label for="password" class="form-label">Nueva contraseña:</label>
                  <input type="password" id="password" name="password" class="form-control" required>
                  </div>
               <button type="submit" class="btn btn-primary w-100">Actualizar contraseña</button>
           </form>
           {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                <div class="mt-2">
                   {% for category, message in messages %}
                       <div class="alert alert-{{ category }}">{{ message }}</div>
                   {% endfor %}
                </div>
              {% endif %}
           {% endwith %}
 <!-- Enlace para volver -->


<!-- Enlace a Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>